project:
  type: book
  output-dir: _book

book:
  title: "From Zero to Production: A Practical Python Development Pipeline"
  author: "Michael Borck"
  date: "last-modified"
  chapters:
    - index.qmd
    - preface.qmd
    - chapters/01-foundation.qmd
    - chapters/02-workflow.qmd
    - chapters/03-documentation.qmd
    - chapters/04-case-study.qmd
    - chapters/05-advanced-techniques.qmd
    - chapters/06-project-management.qmd
    - chapters/07-conclusion.qmd
    - acknowledgments.qmd
    - references.qmd
    - part: "Appendices"
      chapters:
        - appendices/a-checklist.qmd
        - appendices/b-tools.qmd
        - appendices/c-glossary.qmd
        - appendices/d-bash-scaffold-script.qmd
        - appendices/e-cookiecutter.qmd
        - appendices/f-ai-tools.qmd
  page-navigation: true
  sidebar:
    style: docked
    search: true
    collapse-level: 2  # Headings at this level and below will be collapsed
    toc-depth: 3       # Show headings up to this level in sidebar
  repo-url: https://github.com/michael-borck/python-dev-book
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  sharing: [twitter, facebook, linkedin]
  site-url: https://michael-borck.github.io/python-dev-book/

format:
  html:
    theme: cosmo
    code-copy: true
    code-tools: true
    toc: true
    toc-depth: 3
    metadata:
      title: "From Zero to Production: A Practical Python Development Pipeline"
      description: "A comprehensive guide to Python development practices, tools, and workflows"
      keywords: "python, development, best practices, testing, CI/CD, packaging"
    sitemap: true
  pdf:
    documentclass: scrbook
    colorlinks: true
    toc: true
    toc-depth: 3
    cover-image: images/cover.png
  epub:
    toc: true
    toc-depth: 3
    cover-image: images/cover.png