project:
  type: book
  output-dir: _book

book:
  title: "From Zero to Production: A Practical Python Development Pipeline"
  author: "Michael Borck"
  date: "last-modified"
  chapters:
    - index.qmd
    - chapters/01-foundation.qmd
    - chapters/02-workflow.qmd
    - chapters/03-documentation.qmd
    - chapters/04-case-study.qmd
    - chapters/05-advanced-techniques.qmd
    - chapters/06-project-management.qmd
    - chapters/07-conclusion.qmd
    - acknowledgments.qmd
    - references.qmd

  appendices:
    - appendices/a-checklist.qmd
    - appendices/b-tools.qmd
    - appendices/c-glossary.qmd
    - appendices/d-bash-scaffold-script.qmd
    - appendices/e-cookiecutter.qmd
    - appendices/f-ai-tools.qmd

  sidebar:
    style: docked
    search: true
    collapse-level: 2
    toc-depth: 3

  downloads: [pdf, epub]
  repo-url: https://github.com/michael-borck/python-dev-book
  repo-actions: [edit, issue]

website:
  site-url: https://michael-borck.github.io/python-dev-book
  favicon: assets/favicon.png
  open-graph: true

format:
  html:
    theme: cosmo
    cover-image: images/cover.png
    css: styles.css
    downloads: [pdf, epub]
    code-copy: true
    highlight-style: github
    sitemap: true
  pdf:
    documentclass: scrbook
    colorlinks: true
    toc: true
    toc-depth: 3
    cover-image: images/cover.png
  epub:
    toc: true
    toc-depth: 3
    cover-image: images/cover.png

execute:
  enabled: false
  freeze: auto

