project:
  type: book
  output-dir: _book

book:
  title: "From Zero to Production: A Practical Python Development Pipeline"
  author: "Michael Borck"
  date: "last-modified"
  chapters:
    - index.qmd
    - part: "Foundations"
      chapters:
        - chapters/01-foundation.qmd
        - chapters/02-workflow.qmd
        - chapters/03-documentation.qmd
        - chapters/04-case-study.qmd
    - part: "Advanced Techniques"
      chapters:
        - chapters/05-advanced-techniques.qmd
        - chapters/06-project-management.qmd
        - chapters/07-conclusion.qmd
    - acknowledgments.qmd
  appendices:
    - appendices/glossary.qmd
    - appendices/ai-tools.qmd
    - appendices/checklist.qmd
    - appendices/editors.qmd
    - appendices/tools.qmd
    - appendices/tool-comparision.qmd
    - appendices/bash-scaffold-script.qmd
    - appendices/cookiecutter.qmd
    - appendices/hatch.qmd
    - appendices/conda.qmd
    - appendices/venv.qmd
    - appendices/uv.qmd
    - appendices/poetry.qmd
    - appendices/pdm.qmd

  downloads: [pdf, epub]
  repo-url: https://github.com/michael-borck/python-dev-book
  repo-actions: [edit, issue]

website:
  site-url: https://michael-borck.github.io/python-dev-book
  favicon: assets/favicon.png
  open-graph: true

format:
  html:
    theme: cosmo
    cover-image: images/cover.png
    css: styles.css
    downloads: [pdf, epub]
    code-copy: true
    highlight-style: github
    sitemap: true
  pdf:
    documentclass: scrbook
    colorlinks: true
    toc: true
    toc-depth: 3
    cover-image: images/cover.png
  epub:
    toc: true
    toc-depth: 3
    cover-image: images/cover.png

execute:
  enabled: false
  freeze: auto

